export const database = [
  {
    branchID: 'Lazulight',
    debut: '2021/05/16',
    members: [
      {
        name: 'Pomu Rainpuff',
        imageURL: 'https://i.imgur.com/39fUPM3.png',
        channelID: 'UCP4nMSTdwU1KqYWu3UH5DHQ',
        retired: false,
        twitter: 'PomuRainpuff',
      },
      {
        name: 'Elira Pendora',
        imageURL: 'https://i.imgur.com/lBmhwCr.png',
        channelID: 'UCIeSUTOTkF9Hs7q3SGcO-Ow',
        retired: false,
        twitter: 'EliraPendora',
      },
      {
        name: 'Finana Ryugu',
        imageURL: 'https://i.imgur.com/O8SA7sW.png',
        channelID: 'UCu-J8uIXuLZh16gG-cT1naw',
        retired: false,
        twitter: 'FinanaRyugu',
      },
    ],
  },
  {
    branchID: 'OBSYDIA',
    debut: '2021/07/17',
    members: [
      {
        name: 'Rosemi Lovelock',
        imageURL: 'https://i.imgur.com/99POyUo.png',
        channelID: 'UC4WvIIAo89_AzGUh1AZ6Dkg',
        retired: false,
        twitter: 'Rosemi_Lovelock',
      },
      {
        name: 'Petra Gurin',
        imageURL: 'https://i.imgur.com/WjfZvN9.png',
        channelID: 'UCgA2jKRkqpY_8eysPUs8sjw',
        retired: false,
        twitter: 'Petra_Gurin',
      },
      {
        name: 'Selen Tatsuki',
        imageURL: 'https://i.imgur.com/31ICnGl.png',
        channelID: 'UCV1xUwfM2v2oBtT3JNvic3w',
        retired: false,
        twitter: 'Selen_Tatsuki',
      },
    ],
  },
  {
    branchID: 'Ethyria',
    debut: '2021/10/08',
    members: [
      {
        name: 'Nina Kosaka',
        imageURL: 'https://i.imgur.com/khWXnTR.png',
        channelID: 'UCkieJGn3pgJikVW8gmMXE2w',
        retired: false,
        twitter: 'NinaKosaka',
      },
      {
        name: 'Millie Parfait',
        imageURL: 'https://i.imgur.com/X4Sfzmj.png',
        channelID: 'UC47rNmkDcNgbOcM-2BwzJTQ',
        retired: false,
        twitter: 'MillieParfait',
      },
      {
        name: 'Enna Alouette',
        imageURL: 'https://i.imgur.com/CKBWww5.png',
        channelID: 'UCR6qhsLpn62WVxCBK1dkLow',
        retired: false,
        twitter: 'EnnaAlouette',
      },
      {
        name: 'Reimu Endou',
        imageURL: 'https://i.imgur.com/qMgzgBX.png',
        channelID: 'UCBURM8S4LH7cRZ0Clea9RDA',
        retired: false,
        twitter: 'ReimuEndou',
      },
    ],
  },
  {
    branchID: 'Luxiem',
    debut: '2021/12/20',
    members: [
      {
        name: 'Luca Kaneshiro',
        imageURL: 'https://i.imgur.com/s3fu9wk.png',
        channelID: 'UC7Gb7Uawe20QyFibhLl1lzA',
        retired: false,
        twitter: 'luca_kaneshiro',
      },
      {
        name: 'Shu Yamino',
        imageURL: 'https://i.imgur.com/y6zEY0x.png',
        channelID: 'UCG0rzBZV_QMP4MtWg6IjhEA',
        retired: false,
        twitter: 'shu_yamino',
      },
      {
        name: 'Ike Eveland',
        imageURL: 'https://i.imgur.com/RxFHhJP.png',
        channelID: 'UC4yNIKGvy-YUrwYupVdLDXA',
        retired: false,
        twitter: 'ike_eveland',
      },
      {
        name: 'Mysta Rias',
        imageURL: 'https://i.imgur.com/Z1BozxD.png',
        channelID: 'UCIM92Ok_spNKLVB5TsgwseQ',
        retired: false,
        twitter: 'Mysta_Rias',
      },
      {
        name: 'Vox Akuma',
        imageURL: 'https://i.imgur.com/4K5Kj5b.png',
        channelID: 'UCckdfYDGrjojJM28n5SHYrA',
        retired: false,
        twitter: 'Vox_Akuma',
      },
    ],
  },
  {
    branchID: 'Noctyx',
    debut: '2022/02/27',
    members: [
      {
        name: 'Sonny Brisko',
        imageURL: 'https://i.imgur.com/TQyJ6MZ.png',
        channelID: 'UCuuAb_72QzK0M1USPMEl1yw',
        retired: false,
        twitter: 'sonny_brisko',
      },
      {
        name: 'Uki Violeta',
        imageURL: 'https://imgur.com/eiIRsrn.png',
        channelID: 'UChJ5FTsHOu72_5OVx0rvsvQ',
        retired: false,
        twitter: 'uki_violeta',
      },
      {
        name: 'Alban Knox',
        imageURL: 'https://i.imgur.com/3jQw8dS.png',
        channelID: 'UCQ1zGxHrfEmmW4CPpBx9-qw',
        retired: false,
        twitter: 'alban_knox',
      },
      {
        name: 'Fulgur Ovid',
        imageURL: 'https://i.imgur.com/DftQ3fr.png',
        channelID: 'UCGhqxhovNfaPBpxfCruy9EA',
        retired: false,
        twitter: 'Fulgur_Ovid',
      },
      {
        name: 'Yugo Asuma',
        imageURL: 'https://i.imgur.com/mY4a2ak.png',
        channelID: 'UCSc_KzY_9WYAx9LghggjVRA',
        retired: true,
        twitter: 'Yugo_Asuma',
      },
    ],
  },
  {
    branchID: 'ILUNA',
    debut: '2022/07/25',
    members: [
      {
        name: 'Maria Marionette',
        imageURL: 'https://i.imgur.com/qGWqh8t.png',
        channelID: 'UCwaS8_S7kMiKA3izlTWHbQg',
        retired: false,
        twitter: 'MariaMari0nette',
      },
      {
        name: 'Kyo Kaneko',
        imageURL: 'https://i.imgur.com/LZfPU9l.png',
        channelID: 'UCsb-1aJgiJXJH2feV-zlZRw',
        retired: false,
        twitter: 'KyoKanek0',
      },
      {
        name: 'Aia Amare',
        imageURL: 'https://i.imgur.com/MngtTlj.png',
        channelID: 'UCN68LoM3khS4gdBMiWJO8WA',
        retired: false,
        twitter: 'AiaAmare',
      },
      {
        name: 'Aster Arcadia',
        imageURL: 'https://i.imgur.com/iibFRGI.png',
        channelID: 'UCpzxZW5kghGnO5TmAFJQAVw',
        retired: false,
        twitter: 'AsterArcadia',
      },
      {
        name: 'Scarle Yonaguni',
        imageURL: 'https://i.imgur.com/lSbaCGh.png',
        channelID: 'UCFgXWZOUZA2oYHNr6qDmsTQ',
        retired: true,
        twitter: 'scarleyonaguni',
      },
      {
        name: 'Ren Zotto',
        imageURL: 'https://i.imgur.com/rMHg0Qo.png',
        channelID: 'UCKu59gTZ_rdEmerdx5rV4Yg',
        retired: true,
        twitter: 'RenZott0',
      },
    ],
  },
  {
    branchID: 'XSOLEIL',
    debut: '2022/12/10',
    members: [
      {
        name: 'Zaion LanZa',
        imageURL: 'https://i.imgur.com/ELGyqmW.png',
        channelID: 'UCIairB9UMDvqSKfMdv1jmjg',
        retired: false,
        twitter: 'ZaionLanZa',
      },
      {
        name: 'Doppio Dropscythe',
        imageURL: 'https://i.imgur.com/SKJ4Qin.png',
        channelID: 'UCy91xBlY_Brh3bnHxKtjrrg',
        retired: false,
        twitter: 'D_Dropscythe',
      },
      {
        name: 'Meloco Kyoran',
        imageURL: 'https://i.imgur.com/Tb74c6l.png',
        channelID: 'UChKXd7oqD18qiIYBoRIHTlw',
        retired: false,
        twitter: 'MelocoKyoran',
      },
      {
        name: 'Hex Haywire',
        imageURL: 'https://i.imgur.com/PV7KfPU.png',
        channelID: 'UCz_ZRw6ak4Foy8zZy0kEprQ',
        retired: false,
        twitter: 'HexHaywire',
      },
      {
        name: 'Kotoka Torahime',
        imageURL: 'https://i.imgur.com/HcMh49k.png',
        channelID: 'UCggO2c1unS-oLwTLT0ICywg',
        retired: false,
        twitter: 'KotokaTorahime',
      },
      {
        name: 'Ver Vermillion',
        imageURL: 'https://i.imgur.com/rWzpX7f.png',
        channelID: 'UCO8WcDsF5znr-qsXlzZNpqg',
        retired: false,
        twitter: 'Ver_Vermillion',
      },
    ],
  },
];
