export const database: any = {
  NIJISANJI_EN: [
    {
      branchID: 'Lazulight',
      debut: '2021/05/16',
      members: [
        {
          name: 'Pomu Rainpuff',
          imageURL: 'https://i.imgur.com/39fUPM3.png',
          channelID: 'UCP4nMSTdwU1KqYWu3UH5DHQ',
          retired: false,
          twitter: 'PomuRainpuff',
        },
        {
          name: 'Elira Pendora',
          imageURL: 'https://i.imgur.com/lBmhwCr.png',
          channelID: 'UCIeSUTOTkF9Hs7q3SGcO-Ow',
          retired: false,
          twitter: 'EliraPendora',
        },
        {
          name: 'Finana Ryugu',
          imageURL: 'https://i.imgur.com/O8SA7sW.png',
          channelID: 'UCu-J8uIXuLZh16gG-cT1naw',
          retired: false,
          twitter: 'FinanaRyugu',
        },
      ],
    },
    {
      branchID: 'OBSYDIA',
      debut: '2021/07/17',
      members: [
        {
          name: 'Rosemi Lovelock',
          imageURL: 'https://i.imgur.com/99POyUo.png',
          channelID: 'UC4WvIIAo89_AzGUh1AZ6Dkg',
          retired: false,
          twitter: 'Rosemi_Lovelock',
        },
        {
          name: 'Petra Gurin',
          imageURL: 'https://i.imgur.com/WjfZvN9.png',
          channelID: 'UCgA2jKRkqpY_8eysPUs8sjw',
          retired: false,
          twitter: 'Petra_Gurin',
        },
        {
          name: 'Selen Tatsuki',
          imageURL: 'https://i.imgur.com/31ICnGl.png',
          channelID: 'UCV1xUwfM2v2oBtT3JNvic3w',
          retired: false,
          twitter: 'Selen_Tatsuki',
        },
      ],
    },
    {
      branchID: 'Ethyria',
      debut: '2021/10/08',
      members: [
        {
          name: 'Nina Kosaka',
          imageURL: 'https://i.imgur.com/khWXnTR.png',
          channelID: 'UCkieJGn3pgJikVW8gmMXE2w',
          retired: false,
          twitter: 'NinaKosaka',
        },
        {
          name: 'Millie Parfait',
          imageURL: 'https://i.imgur.com/X4Sfzmj.png',
          channelID: 'UC47rNmkDcNgbOcM-2BwzJTQ',
          retired: false,
          twitter: 'MillieParfait',
        },
        {
          name: 'Enna Alouette',
          imageURL: 'https://i.imgur.com/CKBWww5.png',
          channelID: 'UCR6qhsLpn62WVxCBK1dkLow',
          retired: false,
          twitter: 'EnnaAlouette',
        },
        {
          name: 'Reimu Endou',
          imageURL: 'https://i.imgur.com/qMgzgBX.png',
          channelID: 'UCBURM8S4LH7cRZ0Clea9RDA',
          retired: false,
          twitter: 'ReimuEndou',
        },
      ],
    },
    {
      branchID: 'Luxiem',
      debut: '2021/12/20',
      members: [
        {
          name: 'Luca Kaneshiro',
          imageURL: 'https://i.imgur.com/s3fu9wk.png',
          channelID: 'UC7Gb7Uawe20QyFibhLl1lzA',
          retired: false,
          twitter: 'luca_kaneshiro',
        },
        {
          name: 'Shu Yamino',
          imageURL: 'https://i.imgur.com/y6zEY0x.png',
          channelID: 'UCG0rzBZV_QMP4MtWg6IjhEA',
          retired: false,
          twitter: 'shu_yamino',
        },
        {
          name: 'Ike Eveland',
          imageURL: 'https://i.imgur.com/RxFHhJP.png',
          channelID: 'UC4yNIKGvy-YUrwYupVdLDXA',
          retired: false,
          twitter: 'ike_eveland',
        },
        {
          name: 'Mysta Rias',
          imageURL: 'https://i.imgur.com/Z1BozxD.png',
          channelID: 'UCIM92Ok_spNKLVB5TsgwseQ',
          retired: false,
          twitter: 'Mysta_Rias',
        },
        {
          name: 'Vox Akuma',
          imageURL: 'https://i.imgur.com/4K5Kj5b.png',
          channelID: 'UCckdfYDGrjojJM28n5SHYrA',
          retired: false,
          twitter: 'Vox_Akuma',
        },
      ],
    },
    {
      branchID: 'Noctyx',
      debut: '2022/02/27',
      members: [
        {
          name: 'Sonny Brisko',
          imageURL: 'https://i.imgur.com/TQyJ6MZ.png',
          channelID: 'UCuuAb_72QzK0M1USPMEl1yw',
          retired: false,
          twitter: 'sonny_brisko',
        },
        {
          name: 'Uki Violeta',
          imageURL: 'https://imgur.com/eiIRsrn.png',
          channelID: 'UChJ5FTsHOu72_5OVx0rvsvQ',
          retired: false,
          twitter: 'uki_violeta',
        },
        {
          name: 'Alban Knox',
          imageURL: 'https://i.imgur.com/3jQw8dS.png',
          channelID: 'UCQ1zGxHrfEmmW4CPpBx9-qw',
          retired: false,
          twitter: 'alban_knox',
        },
        {
          name: 'Fulgur Ovid',
          imageURL: 'https://i.imgur.com/DftQ3fr.png',
          channelID: 'UCGhqxhovNfaPBpxfCruy9EA',
          retired: false,
          twitter: 'Fulgur_Ovid',
        },
        {
          name: 'Yugo Asuma',
          imageURL: 'https://i.imgur.com/mY4a2ak.png',
          channelID: 'UCSc_KzY_9WYAx9LghggjVRA',
          retired: true,
          twitter: 'Yugo_Asuma',
        },
      ],
    },
    {
      branchID: 'ILUNA',
      debut: '2022/07/25',
      members: [
        {
          name: 'Maria Marionette',
          imageURL: 'https://i.imgur.com/qGWqh8t.png',
          channelID: 'UCwaS8_S7kMiKA3izlTWHbQg',
          retired: false,
          twitter: 'MariaMari0nette',
        },
        {
          name: 'Kyo Kaneko',
          imageURL: 'https://i.imgur.com/LZfPU9l.png',
          channelID: 'UCsb-1aJgiJXJH2feV-zlZRw',
          retired: false,
          twitter: 'KyoKanek0',
        },
        {
          name: 'Aia Amare',
          imageURL: 'https://i.imgur.com/MngtTlj.png',
          channelID: 'UCN68LoM3khS4gdBMiWJO8WA',
          retired: false,
          twitter: 'AiaAmare',
        },
        {
          name: 'Aster Arcadia',
          imageURL: 'https://i.imgur.com/iibFRGI.png',
          channelID: 'UCpzxZW5kghGnO5TmAFJQAVw',
          retired: false,
          twitter: 'AsterArcadia',
        },
        {
          name: 'Scarle Yonaguni',
          imageURL: 'https://i.imgur.com/lSbaCGh.png',
          channelID: 'UCFgXWZOUZA2oYHNr6qDmsTQ',
          retired: true,
          twitter: 'scarleyonaguni',
        },
        {
          name: 'Ren Zotto',
          imageURL: 'https://i.imgur.com/rMHg0Qo.png',
          channelID: 'UCKu59gTZ_rdEmerdx5rV4Yg',
          retired: true,
          twitter: 'RenZott0',
        },
      ],
    },
    {
      branchID: 'XSOLEIL',
      debut: '2022/12/10',
      members: [
        {
          name: 'Zaion LanZa',
          imageURL: 'https://i.imgur.com/ELGyqmW.png',
          channelID: 'UCIairB9UMDvqSKfMdv1jmjg',
          retired: false,
          twitter: 'ZaionLanZa',
        },
        {
          name: 'Doppio Dropscythe',
          imageURL: 'https://i.imgur.com/SKJ4Qin.png',
          channelID: 'UCy91xBlY_Brh3bnHxKtjrrg',
          retired: false,
          twitter: 'D_Dropscythe',
        },
        {
          name: 'Meloco Kyoran',
          imageURL: 'https://i.imgur.com/Tb74c6l.png',
          channelID: 'UChKXd7oqD18qiIYBoRIHTlw',
          retired: false,
          twitter: 'MelocoKyoran',
        },
        {
          name: 'Hex Haywire',
          imageURL: 'https://i.imgur.com/PV7KfPU.png',
          channelID: 'UCz_ZRw6ak4Foy8zZy0kEprQ',
          retired: false,
          twitter: 'HexHaywire',
        },
        {
          name: 'Kotoka Torahime',
          imageURL: 'https://i.imgur.com/HcMh49k.png',
          channelID: 'UCggO2c1unS-oLwTLT0ICywg',
          retired: false,
          twitter: 'KotokaTorahime',
        },
        {
          name: 'Ver Vermillion',
          imageURL: 'https://i.imgur.com/rWzpX7f.png',
          channelID: 'UCO8WcDsF5znr-qsXlzZNpqg',
          retired: false,
          twitter: 'Ver_Vermillion',
        },
      ],
    },
  ],
  HOLOLIVE_EN: [
    {
      branchID: 'Myth',
      debut: '2021/09/12',
      members: [
        {
          name: 'Mori Calliope',
          imageURL: 'https://i.imgur.com/v85ZhQa.png',
          channelID: 'UCL_qhgtOy0dy1Agp8vkySQg',
          retired: false,
          twitter: 'moricalliope',
        },
        {
          name: 'Takanashi Kiara',
          imageURL: 'https://i.imgur.com/8tyIhgw.png',
          channelID: 'UCHsx4Hqa-1ORjQTh9TYDhww',
          retired: false,
          twitter: 'takanashikiara',
        },
        {
          name: "Ninomae Ina'nis",
          imageURL: 'https://i.imgur.com/HtQJ7Nl.png',
          channelID: 'UCMwGHR0BTZuLsmjY_NT5Pwg',
          retired: false,
          twitter: 'ninomaeinanis',
        },
        {
          name: 'Gawr Gura',
          imageURL: 'https://i.imgur.com/eeTTQOv.png',
          channelID: 'UCoSrY_IQQVpmIRZ9Xf-y93g',
          retired: false,
          twitter: 'gawrgura',
        },
        {
          name: 'Watson Amelia',
          imageURL: 'https://i.imgur.com/VFSE02X.png',
          channelID: 'UCyl1z3jo3XHR1riLFKG5UAg',
          retired: false,
          twitter: 'watsonameliaEN',
        },
      ],
    },
    {
      branchID: 'Project: HOPE',
      debut: '2021/09/12',
      members: [
        {
          name: 'IRyS',
          imageURL: 'https://i.imgur.com/oU2seLw.png',
          channelID: 'UC8rcEBzJSleTkf_-agPM20g',
          retired: false,
          twitter: 'irys_en',
        },
      ],
    },
    {
      branchID: 'Council',
      debut: '2021/08/23',
      members: [
        {
          name: 'Ceres Fauna',
          imageURL: 'https://i.imgur.com/EWkunWz.png',
          channelID: 'UCO_aKKYxn4tvrqPjcTzZ6EQ',
          retired: false,
          twitter: 'ceresfauna',
        },
        {
          name: 'Ouro Kronii',
          imageURL: 'https://i.imgur.com/iWzdAc0.png',
          channelID: 'UCmbs8T6MWqUHP1tIQvSgKrg',
          retired: false,
          twitter: 'ourokronii',
        },
        {
          name: 'Nanashi Mumei',
          imageURL: 'https://i.imgur.com/n9LMWQz.png',
          channelID: 'UC3n5uGu18FoCy23ggWWp8tA',
          retired: false,
          twitter: 'nanashimumei_en',
        },
        {
          name: 'Hakos Baelz',
          imageURL: 'https://i.imgur.com/isPxi2Q.png',
          channelID: 'UCgmPnx-EEeOrZSg5Tiw7ZRQ',
          retired: false,
          twitter: 'hakosbaelz',
        },
        {
          name: 'Tsukumo Sana',
          imageURL: 'https://i.imgur.com/wiXKSsB.png',
          channelID: 'UCsUj0dszADCGbF3gNrQEuSQ',
          retired: true,
          twitter: 'tsukumosana',
        },
      ],
    },
    {
      branchID: 'TEMPUS',
      debut: '2022/07/22',
      members: [
        {
          name: 'Regis Altare',
          imageURL: 'https://i.imgur.com/ghDjE1V.png',
          channelID: 'UCyxtGMdWlURZ30WSnEjDOQw',
          retired: false,
          twitter: 'regisaltare',
        },
        {
          name: 'Magni Dezmond',
          imageURL: 'https://i.imgur.com/ml0NMRU.png',
          channelID: 'UC7MMNHR-kf9EN1rXiesMTMw',
          retired: false,
          twitter: 'magnidezmond',
        },
        {
          name: 'Axel Syrios',
          imageURL: 'https://i.imgur.com/Gs7Lnrp.png',
          channelID: 'UC2hx0xVkMoHGWijwr_lA01w',
          retired: false,
          twitter: 'axelsyrios',
        },
        {
          name: 'Noir Vesper',
          imageURL: 'https://i.imgur.com/xWr5yDU.png',
          channelID: 'UCDRWSO281bIHYVi-OV3iFYA',
          retired: false,
          twitter: 'noirvesper_en',
        },
      ],
    },
  ],
  HOLOLIVE_JP: [
    {
      branchID: 'Generation 0',
      debut: '2017/09/07',
      members: [
        {
          name: 'Tokino Sora',
          imageURL: 'https://i.imgur.com/N3NVlVj.png',
          channelID: 'UCp6993wxpyDPHUpavwDFqgg',
          retired: false,
          twitter: 'tokino_sora',
        },
        {
          name: 'Roboco-san',
          imageURL: 'https://i.imgur.com/wfe3x7u.png',
          channelID: 'UCDqI2jOz0weumE8s7paEk6g',
          retired: false,
          twitter: 'robocosan',
        },
        {
          name: 'Sakura Miko',
          imageURL: 'https://i.imgur.com/mdnYpH5.png',
          channelID: 'UC-hM6YJuNYVAmUWxeIr9FeA',
          retired: false,
          twitter: 'sakuramiko35',
        },
        {
          name: 'Hoshimachi Suisei',
          imageURL: 'https://i.imgur.com/tea27eG.png',
          channelID: 'UC5CwaMl1eIgY8h02uZw7u8A',
          retired: false,
          twitter: 'suisei_hosimati',
        },
        {
          name: 'AZKi',
          imageURL: 'https://i.imgur.com/XLQfjQN.png',
          channelID: 'UC0TXe_LYZ4scaW2XMyi5_kw',
          retired: false,
          twitter: 'AZKi_VDiVA',
        },
      ],
    },
    {
      branchID: '1st Generation',
      debut: '2018/05/13',
      members: [
        {
          name: 'Yozora Mel',
          imageURL: 'https://i.imgur.com/vU1xPmL.png',
          channelID: 'UCD8HOxPs4Xvsm8H0ZxXGiBw',
          retired: false,
          twitter: 'yozoramel',
        },
        {
          name: 'Shirakami Fubuki',
          imageURL: 'https://i.imgur.com/Ah9quN6.png',
          channelID: 'UCdn5BQ06XqgXoAxIhbqw5Rg',
          retired: false,
          twitter: 'shirakamifubuki',
        },
        {
          name: 'Natsuiro Matsuri',
          imageURL: 'https://i.imgur.com/XmRjuFg.png',
          channelID: 'UCQ0UDLQCjY0rmuxCDE38FGg',
          retired: false,
          twitter: 'natsuiromatsuri',
        },
        {
          name: 'Akai Haato',
          imageURL: 'https://i.imgur.com/xNUZJjn.png',
          channelID: 'UC1CfXB_kRs3C-zaeTG3oGyg',
          retired: false,
          twitter: 'akaihaato',
        },
        {
          name: 'Aki Rosenthal',
          imageURL: 'https://i.imgur.com/PDuKuT8.png',
          channelID: 'UCFTLzh12_nrtzqBPsTCqenA',
          retired: false,
          twitter: 'akirosenthal',
        },
      ],
    },
    {
      branchID: '2nd Generation',
      debut: '2018/08/08',
      members: [
        {
          name: 'Minato Aqua',
          imageURL: 'https://i.imgur.com/G1PA3yA.png',
          channelID: 'UC1opHUrw8rvnsadT-iGp7Cg',
          retired: false,
          twitter: 'minatoaqua',
        },
        {
          name: 'Murasaki Shion',
          imageURL: 'https://i.imgur.com/WARku94.png',
          channelID: 'UCXTpFs_3PqI41qX2d9tL2Rw',
          retired: false,
          twitter: 'murasakishionch',
        },
        {
          name: 'Nakiri Ayame',
          imageURL: 'https://i.imgur.com/FXLSWc3.png',
          channelID: 'UC7fk0CB07ly8oSl0aqKkqFg',
          retired: false,
          twitter: 'nakiriayame',
        },
        {
          name: 'Yuzuki Choco',
          imageURL: 'https://i.imgur.com/4hcsAX8.png',
          channelID: 'UC1suqwovbL1kzsoaZgFZLKg',
          retired: false,
          twitter: 'yuzukichococh',
        },
        {
          name: 'Oozora Subaru',
          imageURL: 'https://i.imgur.com/HSLgJiH.png',
          channelID: 'UCvzGlP9oQwU--Y0r9id_jnA',
          retired: false,
          twitter: 'oozorasubaru',
        },
      ],
    },
    {
      branchID: '3rd Generation',
      debut: '2019/07/17',
      members: [
        {
          name: 'Usada Pekora',
          imageURL: 'https://i.imgur.com/028fAN8.png',
          channelID: 'UC1DCedRgGHBdm81E1llLhOQ',
          retired: false,
          twitter: 'usadapekora',
        },
        {
          name: 'Shiranui Flare',
          imageURL: 'https://i.imgur.com/20vCco7.png',
          channelID: 'UCvInZx9h3jC2JzsIzoOebWg',
          retired: false,
          twitter: 'shiranuiflare',
        },
        {
          name: 'Shirogane Noel',
          imageURL: 'https://i.imgur.com/keDcBzZ.png',
          channelID: 'UCdyqAaZDKHXg4Ahi7VENThQ',
          retired: false,
          twitter: 'shiroganenoel',
        },
        {
          name: 'Houshou Marine',
          imageURL: 'https://i.imgur.com/yX2QYhu.png',
          channelID: 'UCCzUftO8KOVkV4wQG1vkUvg',
          retired: false,
          twitter: 'houshoumarine',
        },
        {
          name: 'Uruha_Rushia',
          imageURL: 'https://i.imgur.com/bFaSJ1U.png',
          channelID: 'UCl_gCybOJRIgOXw6Qb4qJzQ',
          retired: true,
          twitter: 'uruharushia',
        },
      ],
    },
    {
      branchID: '4th Generation',
      debut: '2019/12/27',
      members: [
        {
          name: 'Amane Kanata',
          imageURL: 'https://i.imgur.com/NSmZSFy.png',
          channelID: 'UCZlDXzGoo7d44bwdNObFacg',
          retired: false,
          twitter: 'amanekanatach',
        },
        {
          name: 'Tsunomaki Watame',
          imageURL: 'https://i.imgur.com/Eos5jzf.png',
          channelID: 'UCqm3BQLlJfvkTsX_hvm0UmA',
          retired: false,
          twitter: 'tsunomakiwatame',
        },
        {
          name: 'Tokoyami Towa',
          imageURL: 'https://i.imgur.com/RjQs5ex.png',
          channelID: 'UC1uv2Oq6kNxgATlCiez59hw',
          retired: false,
          twitter: 'tokoyamitowa',
        },
        {
          name: 'Himemori Luna',
          imageURL: 'https://i.imgur.com/IvNGwe5.png',
          channelID: 'UCa9Y57gfeY0Zro_noHRVrnw',
          retired: false,
          twitter: 'himemoriluna',
        },
        {
          name: 'Kiryu Coco',
          imageURL: 'https://i.imgur.com/KsMzN04.png',
          channelID: 'UCS9uQI-jC3DE0L4IpXyvr6w',
          retired: true,
          twitter: 'kiryucoco',
        },
      ],
    },
    {
      branchID: '5th Generation',
      debut: '2020/08/12',
      members: [
        {
          name: 'Yukihana Lamy',
          imageURL: 'https://i.imgur.com/o57ufUI.png',
          channelID: 'UCFKOVgVbGmX65RxO3EtH3iw',
          retired: false,
          twitter: 'yukihanalamy',
        },
        {
          name: 'Momosuzu Nene',
          imageURL: 'https://i.imgur.com/L6dmrk0.png',
          channelID: 'UCAWSyEs_Io8MtpY3m-zqILA',
          retired: false,
          twitter: 'momosuzunene',
        },
        {
          name: 'Shishiro Botan',
          imageURL: 'https://i.imgur.com/HWbaBla.png',
          channelID: 'UCUKD-uaobj9jiqB-VXt71mA',
          retired: false,
          twitter: 'shishirobotan',
        },
        {
          name: 'Omaru Polka',
          imageURL: 'https://i.imgur.com/tYlKKka.png',
          channelID: 'UCK9V2B22uJYu3N7eR_BT9QA',
          retired: false,
          twitter: 'omarupolka',
        },
        {
          name: 'Mano Aloe',
          imageURL: 'https://i.imgur.com/x8AvEbG.png',
          channelID: 'UCgZuwn-O7Szh9cAgHqJ6vjw',
          retired: true,
          twitter: 'manoaloe',
        },
      ],
    },
    {
      branchID: 'Secret Society holoX',
      debut: '2021/11/26',
      members: [
        {
          name: 'La+ Darknesss',
          imageURL: 'https://i.imgur.com/idpgsIM.png',
          channelID: 'UCENwRMx5Yh42zWpzURebzTw',
          retired: false,
          twitter: 'LaplusDarknesss',
        },
        {
          name: 'Takane Lui',
          imageURL: 'https://i.imgur.com/FeYFXq3.png',
          channelID: 'UCs9_O1tRPMQTHQ-N_L6FU2g',
          retired: false,
          twitter: 'takanelui',
        },
        {
          name: 'Hakui Koyori',
          imageURL: 'https://i.imgur.com/iMRilx9.png',
          channelID: 'UC6eWCld0KwmyHFbAqK3V-Rw',
          retired: false,
          twitter: 'hakuikoyori',
        },
        {
          name: 'Sakamata Chloe',
          imageURL: 'https://i.imgur.com/tAy7wez.png',
          channelID: 'UCIBY1ollUsauvVi4hW4cumw',
          retired: false,
          twitter: 'sakamatachloe',
        },
        {
          name: 'Kazama Iroha',
          imageURL: 'https://i.imgur.com/nLQY0h6.png',
          channelID: 'UC_vMYWcDjmfdpH6r4TTn1MQ',
          retired: true,
          twitter: 'kazamairohach',
        },
      ],
    },
  ],
  // NIJISANJI_JP: {},
};
